data:
  validation_path: './data/eval/eval_dataset.csv'
  training_path: './data/train/train_dataset.csv'


  lycos2017_features: ['flow_id', 'src_addr', 'src_port','dst_addr','dst_port','ip_prot','timestamp','flow_duration','down_up_ratio','pkt_len_max',
    'pkt_len_min','pkt_len_mean','pkt_len_var','pkt_len_std','bytes_per_s','pkt_per_s','fwd_pkt_per_s','bwd_pkt_per_s','fwd_pkt_cnt' ,
    'fwd_pkt_len_tot','fwd_pkt_len_max','fwd_pkt_len_min','fwd_pkt_len_mean','fwd_pkt_len_std','fwd_pkt_hdr_len_tot','fwd_pkt_hdr_len_min',
    'fwd_non_empty_pkt_cnt','bwd_pkt_cnt','bwd_pkt_len_tot','bwd_pkt_len_max','bwd_pkt_len_min','bwd_pkt_len_mean','bwd_pkt_len_std',
    'bwd_pkt_hdr_len_tot','bwd_pkt_hdr_len_min','bwd_non_empty_pkt_cnt','iat_max','iat_min','iat_mean','iat_std','fwd_iat_tot','fwd_iat_max','fwd_iat_min','fwd_iat_mean','fwd_iat_std','bwd_iat_tot','bwd_iat_max',
    'bwd_iat_min','bwd_iat_mean','bwd_iat_std','active_max','active_min','active_mean','active_std','idle_max','idle_min','idle_mean','idle_std','flag_syn','flag_fin','flag_rst','flag_ack','flag_psh','fwd_flag_psh',
    'bwd_flag_psh','flag_urg','fwd_flag_urg','bwd_flag_urg','flag_cwr','flag_ece','fwd_bulk_bytes_mean','fwd_bulk_pkt_mean','fwd_bulk_rate_mean','bwd_bulk_bytes_mean','bwd_bulk_pkt_mean','bwd_bulk_rate_mean',
    'fwd_subflow_bytes_mean','fwd_subflow_pkt_mean','bwd_subflow_bytes_mean','bwd_subflow_pkt_mean','fwd_TCP_init_win_bytes','bwd_TCP_init_win_bytes','label']


  chosen_features: ['dst_addr', 'ip_prot','flow_duration','Total Fwd Packets','Total Length of Fwd Packets','Fwd Packet Length Max',
                    'Fwd Packet Length Min','Fwd Packet Length Mean','Fwd Packet Length Std','Bwd Packet Length Max', 'Bwd Packet Length Min']


  labels: ['SSH-Patator', 'DoS GoldenEye', 'PortScan', 'DoS Slowhttptest', 'Web Attack  Brute Force', 'Bot',
           'Web Attack  Sql Injection', 'Web Attack  XSS', 'Infiltration', 'DDoS',
           'DoS slowloris', 'Heartbleed', 'FTP-Patator', 'DoS Hulk','BENIGN']


graph:
  node_types:
    - name: host_ip
      columns:
        - name: source_ip
          data_column: ['']

        - name: dest_ip
          data_column: [ '' ]
    - name: host_ip_port
      columns: ['','']


model:
  number_iterations: 8
  train_epochs: 100

